### ISSUE TITLE
Utils.domLoadScriptSync doesn't appear to work in the latest Framer Studio 1.9.27

### ISSUE THREAD

**Issue by aroscoe** [koenbok/Framer#139]
I don't know which version this stopped working but a few versions ago everything worked fine. Now when I try to use Utils.domLoadScriptSync it throws a script error. The error reads, "XMLHttpRequest cannot load: Cross origin requests are only supported for HTTP." It also doesn't autocomplete anymore.

**Comment by sogko** [comment]
I'm facing similar issue, things stopped working after re-importing updates from Sketch.

Below are the logs from the Inspector

```
FramerStudio.compile
Utils.coffee:387XMLHttpRequest cannot load file:///Users/sogko/Desktop/App.framer/imported/AppView/layers.json. Cross origin requests are only supported for HTTP.
Utils.coffee:389XMLHttpRequest.error 
XMLHttpRequestException
framer.generated.js:83Eval error: Script error.  0 0
Utils.coffee:396Error: Utils.domLoadDataSync: no data was loaded (url not found?)
framer.generated.js:92Error: Script error.
```

**Comment by koenbok** [comment]
This is new in WebKit2 and considered a bug. I'm waiting for the latest WebKit to include a new function so I can fix it.

**Comment by sogko** [comment]
Just to share some updates/workarounds:

It turns out that for my case, the problem manifests itself for me when I have multiple Sketch files opened.

To workaround the above error, I have to do the following:

1. close Sketch and Framer Studio application

**Comment by uxdiogenes** [comment]
Anyone have the link for the WebKit bug handy?

**Comment by koenbok** [comment]
https://bugs.webkit.org/show_bug.cgi?id=137153

We're just waiting for it to land.

https://twitter.com/koenbok/status/558658911465926656

**Comment by uxdiogenes** [comment]
Is there any workaround in the meantime, e.g. loading a file from a server instead? It would be easy to run a local server/load something from the web, and then it would work once published/shared and not running just locally in Framer Studio anymore, I should think.

**Comment by koenbok** [comment]
I tried to work around it with the old C api (see the tweet) but apparently you can't. The other two options are a custom webkit and what you suggest. Both a lot of work that I rather spend somewhere else. So for now I'm going to wait a bit more for the fix to land, it shouldn't take too long.
